-- Migration 017: Table alterations (add columns to existing tables)

ALTER TABLE assignments
  ADD COLUMN IF NOT EXISTS rubric_url TEXT,
  ADD COLUMN IF NOT EXISTS rubric_file_name TEXT,
  ADD COLUMN IF NOT EXISTS rubric_criteria JSONB,
  ADD COLUMN IF NOT EXISTS max_score NUMERIC DEFAULT 100,
  ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'General',
  ADD COLUMN IF NOT EXISTS tags TEXT[];

ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS is_late BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS regraded_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS regrade_note TEXT;

ALTER TABLE enrollment_records
  ADD COLUMN IF NOT EXISTS grade_level TEXT;

ALTER TABLE announcements
  ADD COLUMN IF NOT EXISTS target_scope TEXT NOT NULL DEFAULT 'all',
  ADD COLUMN IF NOT EXISTS target_id UUID,
  ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

ALTER TABLE schedules
  ADD COLUMN IF NOT EXISTS reschedule_proposed_date DATE,
  ADD COLUMN IF NOT EXISTS reschedule_proposed_start TIME,
  ADD COLUMN IF NOT EXISTS reschedule_proposed_end TIME;

ALTER TABLE chat_messages
  ADD COLUMN IF NOT EXISTS reply_to_id UUID REFERENCES chat_messages(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reactions JSONB NOT NULL DEFAULT '{}';

ALTER TABLE gamified_quizzes
  ADD COLUMN IF NOT EXISTS publish_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS max_attempts INTEGER;
