import { useEffect, useMemo, useState } from 'react';
import { Heart, RotateCcw, Shield, Swords, Timer, Undo2, Zap } from 'lucide-react';
import { ArcadeGameDetail } from '@/app/types/models';

type Response = { answer?: string; choiceId?: string; pairKey?: string };
type Props = { game: ArcadeGameDetail; onClose: () => void; onSubmit: (responses: Response[]) => Promise<void> };

const shuffle = <T,>(items: T[]) => [...items].sort(() => Math.random() - 0.5);

export function ArcadeGamePlayer({ game, onClose, onSubmit }: Props) {
  const [step, setStep] = useState(0);
  const [responses, setResponses] = useState<Response[]>(game.content.map(() => ({})));
  const [seconds, setSeconds] = useState(game.content[0]?.timeLimitSeconds || 20);
  const [selectedLeft, setSelectedLeft] = useState<number | null>(null);
  const [matches, setMatches] = useState<Record<number, number>>({});
  const [flipped, setFlipped] = useState<number[]>([]);
  const [matched, setMatched] = useState<number[]>([]);
  const [hearts, setHearts] = useState(3);
  const [submitting, setSubmitting] = useState(false);
  const item = game.content[step] || {};

  useEffect(() => {
    setSeconds(item.timeLimitSeconds || 20);
  }, [step, item.timeLimitSeconds]);

  useEffect(() => {
    if (game.gameType !== 'speed_run' || seconds <= 0 || submitting) return;
    const timer = window.setTimeout(() => setSeconds((value) => value - 1), 1000);
    return () => window.clearTimeout(timer);
  }, [game.gameType, seconds, submitting]);

  const advance = (response: Response) => {
    const next = responses.map((value, index) => index === step ? response : value);
    setResponses(next);
    if (step < game.content.length - 1) setStep((value) => value + 1);
  };
  const finish = async () => { setSubmitting(true); await onSubmit(responses); setSubmitting(false); };
  const matchCards = useMemo(() => shuffle(game.content), [game.content]);
  const memoryCards = useMemo(() => shuffle(game.content.flatMap((value) => [{ ...value, side: 'term' }, { ...value, side: 'match', cardText: value.rightText || value.cardText } ])), [game.content]);

  const renderSpeedRun = () => <div className="space-y-4"><div className="flex items-center justify-between rounded-xl bg-orange-100 px-4 py-3 font-black text-orange-800"><span>Round {step + 1} of {game.content.length}</span><span className={seconds <= 5 ? 'text-red-600' : ''}><Timer className="mr-1 inline h-4 w-4" />{seconds}s</span></div><div className="rounded-2xl border-2 border-orange-100 bg-orange-50 p-6"><p className="mb-5 text-xl font-black">{item.prompt}</p><div className="grid grid-cols-2 gap-3">{(item.choices || []).map((choice: any) => <button key={choice.id} disabled={seconds === 0} onClick={() => advance({ choiceId: choice.id })} className="rounded-xl border-2 border-white bg-white p-4 text-left font-bold shadow-sm hover:border-orange-400">{choice.text}</button>)}</div></div></div>;

  const renderMatchMaster = () => <div className="rounded-2xl bg-cyan-50 p-5"><p className="mb-4 font-bold text-cyan-900">Select a word, then select its matching meaning.</p><div className="relative grid grid-cols-2 gap-10"><div className="space-y-3">{game.content.map((value: any, index) => <button key={value.id} onClick={() => setSelectedLeft(index)} className={`relative z-10 w-full rounded-xl border-2 bg-white p-4 text-left font-black ${selectedLeft === index ? 'border-cyan-500 ring-2 ring-cyan-200' : matches[index] !== undefined ? 'border-emerald-400 bg-emerald-50' : 'border-white'}`}>{value.leftText}{matches[index] !== undefined && <span className="ml-2 text-emerald-600">✓</span>}</button>)}</div><div className="space-y-3">{matchCards.map((value: any, rightIndex) => <button key={`${value.id}-right`} onClick={() => { if (selectedLeft === null) return; setMatches((old) => ({ ...old, [selectedLeft]: rightIndex })); setResponses((old) => old.map((response, index) => index === selectedLeft ? { answer: value.rightText } : response)); setSelectedLeft(null); }} className={`relative z-10 w-full rounded-xl border-2 bg-white p-4 text-left font-bold ${Object.values(matches).includes(rightIndex) ? 'border-emerald-400 bg-emerald-50' : 'border-white'}`}>{value.rightText}</button>)}</div><svg className="pointer-events-none absolute inset-0 z-0 h-full w-full" preserveAspectRatio="none">{Object.entries(matches).map(([left, right]) => <path key={left} d={`M 24% ${(Number(left) * 100) / game.content.length + 8}% C 40% ${(Number(left) * 100) / game.content.length + 8}%, 60% ${(Number(right) * 100) / game.content.length + 8}%, 76% ${(Number(right) * 100) / game.content.length + 8}%`} fill="none" stroke="#06b6d4" strokeWidth="3" />)}</svg></div><button onClick={finish} className="mt-5 w-full rounded-xl bg-cyan-600 py-3 font-black text-white">Lock in matches</button></div>;

  const renderWordBuilder = () => { const letters = String(item.scrambledLetters || '').split(''); const answer = responses[step]?.answer || ''; return <div className="rounded-2xl border-2 border-emerald-100 bg-emerald-50 p-6"><p className="text-sm font-bold uppercase text-emerald-700">Meaning</p><p className="mt-1 text-xl font-black">{item.prompt}</p><div className="my-6 flex flex-wrap justify-center gap-2">{letters.map((letter, index) => <button key={`${letter}-${index}`} onClick={() => setResponses((old) => old.map((value, i) => i === step ? { answer: `${answer}${letter}` } : value))} className="h-12 w-12 rounded-xl bg-white text-xl font-black text-emerald-700 shadow">{letter.toUpperCase()}</button>)}</div><div className="flex justify-center gap-2">{Array.from({ length: Math.max(answer.length, letters.length) }).map((_, index) => <span key={index} className="flex h-12 w-10 items-center justify-center border-b-4 border-emerald-600 text-xl font-black">{answer[index] || ''}</span>)}</div><input autoFocus value={answer} onChange={(event) => setResponses((old) => old.map((value, i) => i === step ? { answer: event.target.value } : value))} onKeyDown={(event) => { if (event.key === 'Enter') advance({ answer }); }} className="sr-only" aria-label="Type your answer" /><div className="mt-5 flex justify-center gap-2"><button onClick={() => setResponses((old) => old.map((value, i) => i === step ? { answer: answer.slice(0, -1) } : value))} className="rounded-lg border bg-white px-4 py-2 font-bold"><Undo2 className="mr-1 inline h-4 w-4" />Backspace</button><button onClick={() => setResponses((old) => old.map((value, i) => i === step ? {} : value))} className="rounded-lg border bg-white px-4 py-2 font-bold">Clear</button><button onClick={() => step < game.content.length - 1 ? setStep((value) => value + 1) : void finish()} className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white">{step < game.content.length - 1 ? 'Next' : 'Submit word'}</button></div></div>; };

  const renderMemoryFlip = () => <div className="rounded-2xl bg-purple-50 p-5"><p className="mb-4 font-bold text-purple-900">Find every matching pair. Wrong cards flip back.</p><div className="grid grid-cols-3 gap-3">{memoryCards.map((card: any, index) => { const open = flipped.includes(index) || matched.includes(index); return <button key={`${card.id}-${card.side}-${index}`} onClick={() => { if (open || flipped.length === 2) return; const next = [...flipped, index]; setFlipped(next); if (next.length === 2) { const first = memoryCards[next[0]]; const second = memoryCards[next[1]]; if (first.pairKey === second.pairKey) { setMatched((old) => [...old, ...next]); setFlipped([]); if (matched.length + 2 === memoryCards.length) void finish(); } else window.setTimeout(() => setFlipped([]), 700); } }} className={`aspect-square rounded-2xl border-2 p-2 text-center text-sm font-black transition ${open ? 'border-purple-500 bg-white text-purple-800' : 'border-purple-200 bg-purple-600 text-transparent'}`}>{open ? card.cardText : '✦'}</button>; })}</div></div>;

  const renderBoss = () => <div className="rounded-2xl bg-rose-50 p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-black uppercase text-rose-600">Boss Battle · Stage {step + 1}</p><h3 className="text-2xl font-black">⚔️ {item.bossName || 'The Guardian'}</h3></div><div className="flex gap-1">{[0, 1, 2].map((heart) => <Heart key={heart} className={`h-6 w-6 ${heart < hearts ? 'fill-red-500 text-red-500' : 'text-slate-300'}`} />)}</div></div><div className="mb-5 h-4 overflow-hidden rounded-full bg-white"><div className="h-full w-2/3 bg-red-500 transition-all" /></div><p className="mb-4 text-lg font-black">{item.prompt}</p><input className="w-full rounded-xl border-2 border-white px-4 py-3" placeholder="Answer to attack" value={responses[step]?.answer || ''} onChange={(event) => setResponses((old) => old.map((value, i) => i === step ? { answer: event.target.value } : value))} /><button onClick={() => step < game.content.length - 1 ? (setHearts((value) => Math.max(0, value - 0)), setStep((value) => value + 1)) : void finish()} className="mt-4 w-full rounded-xl bg-rose-600 py-3 font-black text-white"><Swords className="mr-2 inline h-5 w-5" />Attack boss</button></div>;

  const renderQuest = () => <div className="rounded-2xl bg-amber-50 p-6"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-black uppercase text-amber-600">Quest Adventure</p><h3 className="text-2xl font-black">🗺️ {item.title || `Checkpoint ${step + 1}`}</h3></div><div className="flex items-center gap-2 text-sm font-black text-amber-700">{game.content.map((_, index) => <span key={index} className={`h-3 w-3 rounded-full ${index <= step ? 'bg-amber-500' : 'bg-amber-200'}`} />)}</div></div><p className="mb-2 rounded-xl bg-white/70 p-4 text-sm italic">{item.storyText || 'Your journey continues...'}</p><p className="mb-4 text-lg font-black">{item.prompt}</p><input className="w-full rounded-xl border-2 border-white px-4 py-3" placeholder="Solve the checkpoint" value={responses[step]?.answer || ''} onChange={(event) => setResponses((old) => old.map((value, i) => i === step ? { answer: event.target.value } : value))} /><button onClick={() => step < game.content.length - 1 ? setStep((value) => value + 1) : void finish()} className="mt-4 w-full rounded-xl bg-amber-600 py-3 font-black text-white">{step < game.content.length - 1 ? 'Unlock next checkpoint' : 'Complete adventure'}</button></div>;

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase text-indigo-600">{game.gameType.replace('_', ' ')}</p><h2 className="text-3xl font-black">{game.title}</h2></div><button onClick={onClose} className="font-bold text-slate-400">Close</button></div><p className="mt-2 text-sm text-slate-500">Practice mode · unlimited tries · power-ups are available from the shop.</p><div className="mt-6">{game.gameType === 'speed_run' && renderSpeedRun()}{game.gameType === 'match_master' && renderMatchMaster()}{game.gameType === 'word_builder' && renderWordBuilder()}{game.gameType === 'memory_flip' && renderMemoryFlip()}{game.gameType === 'boss_battle' && renderBoss()}{game.gameType === 'quest_adventure' && renderQuest()}</div>{game.gameType !== 'match_master' && game.gameType !== 'memory_flip' && game.gameType !== 'word_builder' && <button disabled={submitting} onClick={() => void finish()} className="mt-5 w-full rounded-xl bg-indigo-600 py-3 font-black text-white">{submitting ? 'Saving...' : 'Finish game and claim rewards'}</button>}</div></div>;
}
