import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { BookOpen, CalendarDays, ClipboardList, Grid2X2, GraduationCap, List, Search, UserRound, Video, X } from "lucide-react";
import { toast } from "sonner";
import { apiClient } from "@/app/services/apiClient";
import type { StudentRecordItem, UserRole } from "@/app/types/models";
import { TablePagination, DEFAULT_TABLE_PAGE_SIZE } from "./ui/table-tools";

interface StudentRecordsProps { role: UserRole }
type RecordTab = "overview" | "academic" | "sessions";
const dateLabel = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString() : "—";

export function StudentRecords({ role }: StudentRecordsProps) {
  const [records, setRecords] = useState<StudentRecordItem[]>([]);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("active");
  const [view, setView] = useState<"cards" | "list">("cards");
  const [selected, setSelected] = useState<StudentRecordItem | null>(null);
  const [tab, setTab] = useState<RecordTab>("overview");
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_TABLE_PAGE_SIZE);

  useEffect(() => { apiClient.listStudentRecords().then(setRecords).catch((error: Error) => toast.error(error.message || "Failed to load student records.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => records.filter((record) => { const student = record.student; const query = search.trim().toLowerCase(); const searchable = [student.fullName, ...record.enrollments.map((item) => `${item.subject} ${item.teacherName} ${item.gradeLevel || ""}`)].join(" ").toLowerCase(); return (!query || searchable.includes(query)) && (!status || student.status === status || record.enrollments.some((item) => item.status === status)); }), [records, search, status]);
  useEffect(() => { setPage(1); }, [search, status]);
  const paginated = useMemo(() => filtered.slice((page - 1) * pageSize, page * pageSize), [filtered, page, pageSize]);
  const openRecord = (record: StudentRecordItem) => { setSelected(record); setTab("overview"); };

  return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6">
    <div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl md:text-3xl font-bold text-gray-900 flex items-center gap-2"><ClipboardList className="h-7 w-7 text-violet-600" />Student Records</h1><p className="text-gray-500 mt-1">{role === "admin" ? "Complete records for all students." : "Complete records for your assigned students."}</p></div><div className="rounded-xl bg-violet-50 p-3"><UserRound className="h-6 w-6 text-violet-600" /></div></div>
    <div className="flex flex-wrap gap-3"><div className="relative flex-1 min-w-[240px]"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search students, subjects, teachers..." className="w-full rounded-xl border border-gray-200 py-2.5 pl-10 pr-4 text-sm focus:outline-none focus:ring-2 focus:ring-violet-500" /></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-gray-200 px-3 py-2.5 text-sm"><option value="active">Active students</option><option value="">All statuses</option><option value="inactive">Inactive</option><option value="pending">Pending</option><option value="archived">Archived</option><option value="completed">Completed enrollment</option><option value="dropped">Dropped enrollment</option></select><div className="flex rounded-xl border border-gray-200 bg-white p-1"><button onClick={() => setView("cards")} aria-label="Card view" className={`rounded-lg p-2 ${view === "cards" ? "bg-violet-100 text-violet-700" : "text-gray-400 hover:text-gray-700"}`}><Grid2X2 className="h-4 w-4" /></button><button onClick={() => setView("list")} aria-label="List view" className={`rounded-lg p-2 ${view === "list" ? "bg-violet-100 text-violet-700" : "text-gray-400 hover:text-gray-700"}`}><List className="h-4 w-4" /></button></div></div>
    <div className={view === "cards" ? "grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4" : "rounded-2xl bg-white border border-gray-100 overflow-hidden"}>{loading ? <div className="col-span-full p-12 text-center text-gray-400">Loading student records...</div> : filtered.length === 0 ? <div className="col-span-full p-12 text-center text-gray-400">No student records found.</div> : view === "cards" ? filtered.map((record) => <StudentCard key={record.student.id} record={record} onClick={() => openRecord(record)} />) : <><div className="divide-y divide-gray-100">{paginated.map((record) => <StudentListRow key={record.student.id} record={record} onClick={() => openRecord(record)} />)}</div><TablePagination page={page} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }} /></>}</div>

    {selected && <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><div className="w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl bg-gray-50 shadow-2xl"><div className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-gray-200 bg-white px-5 py-4 md:px-7"><div className="flex items-center gap-3"><Avatar record={selected} /><div><h2 className="text-xl font-bold text-gray-900">{selected.student.fullName}</h2><p className="text-sm text-gray-500 capitalize">{selected.student.status} · Student since {dateLabel(selected.student.createdAt)}</p></div></div><button onClick={() => setSelected(null)} aria-label="Close student record" className="rounded-lg p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-700"><X /></button></div><div className="border-b border-gray-200 bg-white px-5 md:px-7"><div className="flex gap-5 overflow-x-auto">{([["overview", "Overview"], ["academic", "Assignments & Assessments"], ["sessions", "Schedule & Meetings"]] as [RecordTab, string][]).map(([value, label]) => <button key={value} onClick={() => setTab(value)} className={`whitespace-nowrap border-b-2 px-1 py-3 text-sm font-semibold ${tab === value ? "border-violet-600 text-violet-700" : "border-transparent text-gray-500 hover:text-gray-800"}`}>{label}</button>)}</div></div><div className="p-5 md:p-7">{tab === "overview" && <Overview record={selected} />}{tab === "academic" && <Academic record={selected} />}{tab === "sessions" && <Sessions record={selected} />}</div></div></div>}
  </div>;
}

function Avatar({ record }: { record: StudentRecordItem }) { const { student } = record; return <div className="h-12 w-12 shrink-0 overflow-hidden rounded-full bg-violet-100 text-violet-700 flex items-center justify-center font-bold">{student.profileImageUrl ? <img src={student.profileImageUrl} alt="" className="h-full w-full object-cover" /> : student.fullName.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div>; }
function StudentCard({ record, onClick }: { record: StudentRecordItem; onClick: () => void }) { return <button onClick={onClick} className="text-left rounded-2xl bg-white border border-gray-100 p-5 shadow-sm hover:border-violet-300 hover:shadow-md transition"><div className="flex items-center gap-3"><Avatar record={record} /><div className="min-w-0"><h2 className="font-semibold text-gray-900 truncate">{record.student.fullName}</h2><p className="text-xs text-gray-500 capitalize">{record.student.status} · {record.enrollments.length} enrollment{record.enrollments.length === 1 ? "" : "s"}</p></div></div><Stats record={record} /></button>; }
function StudentListRow({ record, onClick }: { record: StudentRecordItem; onClick: () => void }) { return <button onClick={onClick} className="w-full text-left flex items-center gap-4 px-5 py-4 hover:bg-violet-50/50 transition"><Avatar record={record} /><div className="min-w-0 flex-1"><p className="font-semibold text-gray-900 truncate">{record.student.fullName}</p><p className="text-xs text-gray-500 capitalize">{record.student.status} · {record.enrollments.map((item) => item.subject).join(", ") || "No enrollment"}</p></div><div className="hidden sm:flex items-center gap-5 text-xs text-gray-500"><span>{record.assignments.length} assignments</span><span>{record.gamifiedAttempts.length} quizzes</span><span>{record.schedules.length} sessions</span></div><span className="text-violet-600 text-sm font-semibold">View</span></button>; }
function Stats({ record }: { record: StudentRecordItem }) { return <><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-gray-50 p-2"><span className="block text-gray-400">Mobile</span><span className="font-medium text-gray-700">{record.student.mobileNumber || "—"}</span></div><div className="rounded-lg bg-gray-50 p-2"><span className="block text-gray-400">Birthdate</span><span className="font-medium text-gray-700">{record.student.birthdate ? dateLabel(record.student.birthdate) : "—"}</span></div></div><div className="mt-2 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg bg-blue-50 p-2"><BookOpen className="mx-auto h-4 w-4 text-blue-600" /><span className="block mt-1 text-gray-600">{record.assignments.length} assignments</span></div><div className="rounded-lg bg-emerald-50 p-2"><GraduationCap className="mx-auto h-4 w-4 text-emerald-600" /><span className="block mt-1 text-gray-600">{record.gamifiedAttempts.length} quizzes</span></div><div className="rounded-lg bg-amber-50 p-2"><CalendarDays className="mx-auto h-4 w-4 text-amber-600" /><span className="block mt-1 text-gray-600">{record.schedules.length} sessions</span></div></div></>; }
function Overview({ record }: { record: StudentRecordItem }) { return <><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6"><Info label="First name" value={record.student.firstName} /><Info label="Middle name" value={record.student.middleName || "—"} /><Info label="Last name" value={record.student.lastName} /><div className="rounded-xl bg-white border border-gray-100 p-3"><p className="text-xs text-gray-500">Account status</p><span className={`inline-flex mt-1 rounded-full border px-2 py-1 text-xs font-semibold capitalize ${statusClass(record.student.status)}`}>{record.student.status}</span></div></div><Section title="Enrollment & Class"><div className="space-y-3">{record.enrollments.length ? record.enrollments.map((item) => <div key={item.id} className="rounded-xl bg-white border border-gray-100 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold text-gray-900">{item.subject}</p><p className="text-sm text-gray-500">{item.teacherName} · {item.tutorialGroup || "No group"} · {item.gradeLevel || "No grade level"}</p></div><span className={`text-xs capitalize rounded-full border px-2 py-1 h-fit ${statusClass(item.status)}`}>{item.status}</span></div>{item.note && <p className="text-sm text-gray-500 mt-2">{item.note}</p>}{item.status === 'dropped' && item.dropReason && <p className="text-sm text-red-600 mt-2">Drop reason: {item.dropReason}</p>}</div>) : <Empty text="No enrollment records." />}</div></Section><Section title="Status History"><div className="space-y-2">{record.statusHistory.length ? record.statusHistory.map((item) => <div key={item.id} className="rounded-xl bg-white border border-gray-100 p-3 text-sm"><div className="flex justify-between gap-3"><span className="capitalize font-medium">{item.previousStatus || 'New'} → {item.newStatus}</span><span className="text-xs text-gray-500">{dateLabel(item.createdAt)}</span></div>{item.reason && <p className="text-gray-600 mt-1">{item.reason}</p>}{item.actionTaken && <p className="text-gray-500 mt-1">Action: {item.actionTaken}</p>}</div>) : <Empty text="No status changes recorded." />}</div></Section></>; }
function Academic({ record }: { record: StudentRecordItem }) { return <><Section title="Assignments & Grades"><div className="space-y-2">{record.assignments.length ? record.assignments.map(({ assignment, submission }) => <div key={assignment.id} className="rounded-xl bg-white border border-gray-100 p-4 flex justify-between gap-3"><div><p className="font-medium text-gray-900">{assignment.title}</p><p className="text-xs text-gray-500">Due {dateLabel(assignment.dueDate)} · {submission ? `Submitted ${dateLabel(submission.submittedAt)}` : "Not submitted"}</p>{submission?.feedback && <p className="text-sm text-gray-600 mt-1">Feedback: {submission.feedback}</p>}</div><span className={`font-bold ${submission?.grade ? "text-emerald-600" : "text-gray-400"}`}>{submission?.grade || "—"}</span></div>) : <Empty text="No assignments recorded." />}</div></Section><Section title="Gamified Assessments"><div className="space-y-2">{record.gamifiedAttempts.length ? record.gamifiedAttempts.map((attempt) => <div key={attempt.id} className="rounded-xl bg-white border border-gray-100 p-4 flex justify-between gap-3"><div><p className="font-medium text-gray-900">{attempt.quizTitle}</p><p className="text-xs text-gray-500">{attempt.categoryName} · {dateLabel(attempt.completedAt)}</p></div><span className="font-bold text-violet-600">{attempt.correctAnswers}/{attempt.totalQuestions}<small className="block text-[10px] text-gray-400 text-right">{attempt.totalScore} pts</small></span></div>) : <Empty text="No gamified assessment results." />}</div></Section></>; }
function Sessions({ record }: { record: StudentRecordItem }) { return <><Section title="Schedule"><div className="space-y-2">{record.schedules.length ? record.schedules.map((item) => <div key={item.id} className="rounded-xl bg-white border border-gray-100 p-4"><p className="font-medium text-gray-900">{item.title}</p><p className="text-sm text-gray-500">{dateLabel(item.date)} · {item.startTime}–{item.endTime} · {item.teacherName}</p><p className="text-xs capitalize text-violet-600 mt-1">{item.status}</p></div>) : <Empty text="No scheduled sessions." />}</div></Section><Section title="Video Meeting History"><div className="space-y-2">{record.meetingHistory.length ? record.meetingHistory.map((item) => <div key={item.id} className="rounded-xl bg-white border border-gray-100 p-4 flex items-center gap-3"><Video className="h-5 w-5 text-blue-600" /><div><p className="font-medium text-gray-900">Session with {item.teacherName}</p><p className="text-sm text-gray-500">{dateLabel(item.startedAt)} · {item.durationSeconds != null ? `${Math.floor(item.durationSeconds / 60)}m ${item.durationSeconds % 60}s` : "Duration unavailable"}</p></div></div>) : <Empty text="No video meeting history." />}</div></Section></>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="mb-6"><h3 className="font-semibold text-gray-800 mb-2">{title}</h3>{children}</section>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white border border-gray-100 p-3"><p className="text-xs text-gray-500">{label}</p><p className="font-medium text-gray-900 capitalize mt-1 truncate">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl bg-white border border-dashed border-gray-200 p-4 text-sm text-gray-400">{text}</div>; }
function statusClass(status: string) { return status === 'active' ? 'bg-blue-50 text-blue-700 border-blue-200' : status === 'completed' ? 'bg-green-50 text-green-700 border-green-200' : status === 'dropped' ? 'bg-red-50 text-red-700 border-red-200' : 'bg-gray-50 text-gray-600 border-gray-200'; }
