#!/usr/bin/env python3
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List

from faster_whisper import WhisperModel
from youtube_transcript_api import YouTubeTranscriptApi


DEFAULT_MODEL_SIZE = os.getenv("FASTER_WHISPER_MODEL", "tiny")
DEFAULT_DEVICE = os.getenv("FASTER_WHISPER_DEVICE", "cpu")
DEFAULT_COMPUTE_TYPE = os.getenv("FASTER_WHISPER_COMPUTE_TYPE", "int8")
DEFAULT_LANGUAGE = os.getenv("FASTER_WHISPER_LANGUAGE", "en")


def print_json(payload: Dict) -> None:
    print(json.dumps(payload, ensure_ascii=True))


def normalize_text(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def extract_audio_with_ffmpeg(video_path: str, output_wav: str) -> None:
    ffmpeg_bin = os.getenv("FFMPEG_BINARY", "ffmpeg")
    cmd = [
        ffmpeg_bin,
        "-y",
        "-i",
        video_path,
        "-vn",
        "-ac",
        "1",
        "-ar",
        "16000",
        "-f",
        "wav",
        output_wav,
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def transcribe_audio_file(audio_path: str) -> str:
    model = WhisperModel(DEFAULT_MODEL_SIZE, device=DEFAULT_DEVICE, compute_type=DEFAULT_COMPUTE_TYPE)

    def read_segments(**kwargs) -> str:
        segments, _info = model.transcribe(
            audio_path,
            vad_filter=True,
            beam_size=1,
            best_of=1,
            condition_on_previous_text=False,
            **kwargs,
        )
        lines: List[str] = []
        for segment in segments:
            if segment.text:
                lines.append(segment.text.strip())
        return normalize_text(" ".join(lines))

    transcript = read_segments()
    if not transcript and DEFAULT_LANGUAGE:
        transcript = read_segments(language=DEFAULT_LANGUAGE)

    if not transcript:
        raise RuntimeError("No transcript generated by faster-whisper.")
    return transcript


def fetch_youtube_transcript(video_id: str) -> str:
    api = YouTubeTranscriptApi()
    transcript_items = api.fetch(video_id, languages=[DEFAULT_LANGUAGE, "en"])
    text_parts: List[str] = []

    for item in transcript_items:
        if isinstance(item, dict):
            text_parts.append(str(item.get("text", "")))
        else:
            text_parts.append(str(getattr(item, "text", "")))

    transcript = normalize_text(" ".join(text_parts))
    if not transcript:
        raise RuntimeError("Transcript is empty for this YouTube video.")
    return transcript


def download_youtube_audio(video_url: str, output_dir: str) -> str:
    output_template = str(Path(output_dir) / "youtube_audio.%(ext)s")
    ytdlp_bin = shutil.which("yt-dlp")

    if ytdlp_bin:
        cmd = [
            ytdlp_bin,
            "-f",
            "bestaudio/best",
            "-o",
            output_template,
            video_url,
        ]
    else:
        cmd = [
            sys.executable,
            "-m",
            "yt_dlp",
            "-f",
            "bestaudio/best",
            "-o",
            output_template,
            video_url,
        ]

    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    candidates = sorted(Path(output_dir).glob("youtube_audio.*"))
    if not candidates:
        raise RuntimeError("yt-dlp did not produce an audio file.")
    return str(candidates[0])


def transcribe_video_file(video_path: str) -> str:
    with tempfile.TemporaryDirectory(prefix="yunafied-video-") as tmp:
        wav_path = str(Path(tmp) / "audio.wav")
        extract_audio_with_ffmpeg(video_path, wav_path)
        return transcribe_audio_file(wav_path)


def transcribe_youtube_video(video_url: str) -> str:
    with tempfile.TemporaryDirectory(prefix="yunafied-youtube-") as tmp:
        audio_path = download_youtube_audio(video_url, tmp)
        return transcribe_audio_file(audio_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Video transcription helper for Yunafied")
    subparsers = parser.add_subparsers(dest="command", required=True)

    yt_transcript_parser = subparsers.add_parser("fetch_youtube_transcript")
    yt_transcript_parser.add_argument("--video-id", required=True)

    video_file_parser = subparsers.add_parser("transcribe_video_file")
    video_file_parser.add_argument("--video-path", required=True)

    yt_video_parser = subparsers.add_parser("transcribe_youtube_video")
    yt_video_parser.add_argument("--video-url", required=True)

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    try:
        if args.command == "fetch_youtube_transcript":
            transcript = fetch_youtube_transcript(args.video_id)
            print_json({"transcript": transcript})
            return

        if args.command == "transcribe_video_file":
            transcript = transcribe_video_file(args.video_path)
            print_json({"transcript": transcript})
            return

        if args.command == "transcribe_youtube_video":
            transcript = transcribe_youtube_video(args.video_url)
            print_json({"transcript": transcript})
            return

        print_json({"error": "Unsupported command."})
    except Exception as exc:
        print_json({"error": str(exc)})


if __name__ == "__main__":
    main()
