#!/usr/bin/env python3
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List

from faster_whisper import WhisperModel
from youtube_transcript_api import YouTubeTranscriptApi


DEFAULT_MODEL_SIZE = os.getenv("FASTER_WHISPER_MODEL", "tiny")
DEFAULT_DEVICE = os.getenv("FASTER_WHISPER_DEVICE", "cpu")
DEFAULT_COMPUTE_TYPE = os.getenv("FASTER_WHISPER_COMPUTE_TYPE", "int8")
DEFAULT_LANGUAGE = os.getenv("FASTER_WHISPER_LANGUAGE", "en")


def print_json(payload: Dict) -> None:
    print(json.dumps(payload, ensure_ascii=True))


def normalize_text(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def extract_audio_with_ffmpeg(video_path: str, output_wav: str) -> None:
    ffmpeg_bin = os.getenv("FFMPEG_BINARY", "ffmpeg")
    cmd = [
        ffmpeg_bin,
        "-y",
        "-i",
        video_path,
        "-vn",
        "-ac",
        "1",
        "-ar",
        "16000",
        "-f",
        "wav",
        output_wav,
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def transcribe_audio_file(audio_path: str) -> str:
    model = WhisperModel(DEFAULT_MODEL_SIZE, device=DEFAULT_DEVICE, compute_type=DEFAULT_COMPUTE_TYPE)

    def read_segments(**kwargs) -> str:
        segments, _info = model.transcribe(
            audio_path,
            vad_filter=True,
            beam_size=1,
            best_of=1,
            condition_on_previous_text=False,
            **kwargs,
        )
        lines: List[str] = []
        for segment in segments:
            if segment.text:
                lines.append(segment.text.strip())
        return normalize_text(" ".join(lines))

    transcript = read_segments()
    if not transcript and DEFAULT_LANGUAGE:
        transcript = read_segments(language=DEFAULT_LANGUAGE)

    if not transcript:
        raise RuntimeError("No transcript generated by faster-whisper.")
    return transcript


def fetch_youtube_transcript(video_id: str) -> str:
    api = YouTubeTranscriptApi()
    transcript_items = api.fetch(video_id, languages=[DEFAULT_LANGUAGE, "en"])
    text_parts: List[str] = []

    for item in transcript_items:
        if isinstance(item, dict):
            text_parts.append(str(item.get("text", "")))
        else:
            text_parts.append(str(getattr(item, "text", "")))

    transcript = normalize_text(" ".join(text_parts))
    if not transcript:
        raise RuntimeError("Transcript is empty for this YouTube video.")
    return transcript


def download_youtube_audio(video_url: str, output_dir: str) -> str:
    output_template = str(Path(output_dir) / "youtube_audio.%(ext)s")
    ytdlp_bin = shutil.which("yt-dlp")

    # Optional environment config to handle restricted videos / IP blocks
    # - YTDLP_COOKIES: path to a Netscape cookies.txt file exported from your browser
    # - YTDLP_JS_RUNTIMES: comma-separated JS runtimes to pass to yt-dlp (e.g. "node")
    # - YTDLP_PROXY: proxy URL (e.g. "http://user:pass@host:port")
    cookies_path = os.getenv("YTDLP_COOKIES")
    js_runtimes = os.getenv("YTDLP_JS_RUNTIMES")
    proxy = os.getenv("YTDLP_PROXY")
    # Prefer the yt_dlp Python API when available (more reliable in some environments)
    try:
        import yt_dlp

        ydl_opts = {
            "format": "bestaudio/best",
            "outtmpl": output_template,
            "quiet": True,
            "no_warnings": True,
            "ignoreerrors": False,
            "noplaylist": True,
        }
        if cookies_path:
            ydl_opts["cookiefile"] = cookies_path
        if proxy:
            # yt_dlp supports 'proxy' option
            ydl_opts["proxy"] = proxy

        # Use the API download; some extraction paths may still require a JS runtime
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([video_url])
    except Exception:
        # Fallback to external binary or module invocation
        if ytdlp_bin:
            cmd = [
                ytdlp_bin,
                "-f",
                "bestaudio/best",
                "-o",
                output_template,
                video_url,
            ]
        else:
            cmd = [
                sys.executable,
                "-m",
                "yt_dlp",
                "-f",
                "bestaudio/best",
                "-o",
                output_template,
                video_url,
            ]

        try:
            # Add optional args for cookies, js runtimes, and proxy to the external command
            if cookies_path:
                cmd.extend(["--cookies", cookies_path])
            if js_runtimes:
                cmd.extend(["--js-runtimes", js_runtimes])
            if proxy:
                cmd.extend(["--proxy", proxy])

            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        except subprocess.CalledProcessError as exc:
            stderr_text = exc.stderr.decode("utf-8", errors="ignore") if exc.stderr else str(exc)
            # Detect common failure messages and provide actionable hints
            if "Sign in to confirm you\'re not a bot" in stderr_text or "Sign in to confirm you\u2019re not a bot" in stderr_text:
                raise RuntimeError(
                    "yt-dlp: YouTube is requiring interactive sign-in (captcha). "
                    "You can either: (1) provide a browser cookies file via the YTDLP_COOKIES env var, "
                    "or (2) use a residential proxy via YTDLP_PROXY. Note: both approaches may violate YouTube Terms of Service. "
                    f"Original yt-dlp message: {stderr_text}")
            if "No supported JavaScript runtime could be found" in stderr_text or "No supported JavaScript runtime" in stderr_text:
                raise RuntimeError(
                    "yt-dlp: No JS runtime available. Install Node.js or Deno on the server, or set YTDLP_JS_RUNTIMES to 'node'. "
                    f"Original yt-dlp message: {stderr_text}")
            raise RuntimeError(f"yt-dlp download failed: {stderr_text}")

    candidates = sorted(Path(output_dir).glob("youtube_audio.*"))
    if not candidates:
        raise RuntimeError("yt-dlp did not produce an audio file.")
    return str(candidates[0])


def transcribe_video_file(video_path: str) -> str:
    with tempfile.TemporaryDirectory(prefix="yunafied-video-") as tmp:
        wav_path = str(Path(tmp) / "audio.wav")
        extract_audio_with_ffmpeg(video_path, wav_path)
        return transcribe_audio_file(wav_path)


def transcribe_youtube_video(video_url: str) -> str:
    with tempfile.TemporaryDirectory(prefix="yunafied-youtube-") as tmp:
        audio_path = download_youtube_audio(video_url, tmp)
        return transcribe_audio_file(audio_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Video transcription helper for Yunafied")
    subparsers = parser.add_subparsers(dest="command", required=True)

    yt_transcript_parser = subparsers.add_parser("fetch_youtube_transcript")
    yt_transcript_parser.add_argument("--video-id", required=True)

    video_file_parser = subparsers.add_parser("transcribe_video_file")
    video_file_parser.add_argument("--video-path", required=True)

    yt_video_parser = subparsers.add_parser("transcribe_youtube_video")
    yt_video_parser.add_argument("--video-url", required=True)

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    try:
        if args.command == "fetch_youtube_transcript":
            transcript = fetch_youtube_transcript(args.video_id)
            print_json({"transcript": transcript})
            return

        if args.command == "transcribe_video_file":
            transcript = transcribe_video_file(args.video_path)
            print_json({"transcript": transcript})
            return

        if args.command == "transcribe_youtube_video":
            transcript = transcribe_youtube_video(args.video_url)
            print_json({"transcript": transcript})
            return

        print_json({"error": "Unsupported command."})
    except Exception as exc:
        print_json({"error": str(exc)})


if __name__ == "__main__":
    main()
